services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    # When postgres container starts for the first time, apply prisma migrations and modify VectorEmbedding table
    command: >
      sh -c "
        until pg_isready -h ${POSTGRES_HOST} -U ${POSTGRES_USER}; do
          echo 'Waiting for PostgreSQL...'
          sleep 2
        done &&
        pnpm prisma migrate deploy &&
        echo 'Modifying VectorEmbedding table...' &&
        PGPASSWORD=${POSTGRES_PASSWORD} psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'ALTER TABLE \"VectorEmbedding\" ALTER COLUMN \"embedding\" TYPE vector(512);' &&
        pnpm start
      "

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mysecurepassword

volumes:
  postgres_data:
